# Generated by Django 4.0 on 2022-01-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listItems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validity', models.BooleanField(default=False)),
            ],
        ),
    ]
