# Generated by Django 4.0 on 2022-01-21 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listItems', '0002_searchfield'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchField',
        ),
    ]
