# Generated by Django 4.0 on 2022-01-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listItems', '0003_delete_searchfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=5)),
                ('validity', models.BooleanField(default=True)),
            ],
        ),
    ]
