# Generated by Django 4.0 on 2022-01-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listItems', '0004_searchfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchfield',
            name='is_duplicate',
            field=models.BooleanField(default=True),
        ),
    ]
