# Generated by Django 4.0 on 2022-01-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stock_change_stock_change_p_stock_close_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='stock',
            name='close',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
    ]
