# Generated by Django 4.0 on 2022-01-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_stock_price_alter_stock_close'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='change',
            new_name='open',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='change_p',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='price',
        ),
        migrations.AlterField(
            model_name='stock',
            name='close',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
